name: OSV-Scanner

on:
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 7 * * 1"

jobs:
  scan:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: google/osv-scanner-action/osv-scanner-action@v1
        with:
          scan-args: |-
            --recursive
            ./
